// Generated by CoffeeScript 1.6.2
$(document).ready(function() {
  $("a").click(function() {
    $("html, body").animate({
      scrollTop: $($.attr(this, "href")).offset().top
    }, 1000);
    return false;
  });
  $('#start-hearts').click(function() {
    return hearts(10);
  });
  $('#kill-all-hearts').click(function() {
    return kill_all_hearts();
  });
  return $("img.svg").each(function() {
    var $img, imgClass, imgID, imgURL;

    $img = $(this);
    imgID = $img.attr("id");
    imgClass = $img.attr("class");
    imgURL = $img.attr("src");
    return $.get(imgURL, function(data) {
      var $svg;

      $svg = $(data).find("svg");
      if (typeof imgID !== "undefined") {
        $svg = $svg.attr("id", imgID);
      }
      if (typeof imgClass !== "undefined") {
        $svg = $svg.attr("class", imgClass + " replaced-svg");
      }
      $svg = $svg.removeAttr("xmlns:a");
      return $img.replaceWith($svg);
    });
  });
});
