// Generated by CoffeeScript 1.6.2
var heart_css, hearts, hearts_create_divs, hearts_perlin, hearts_random, hearts_to_center, kill_all_hearts, x, x_displacement, x_inc;

heart_css = ".heart { width: 126px; height: 117px; position: fixed; background-image: url('javascripts/vendor/open-heart/heart.png'); }";

x = 1;

x_inc = 1;

x_displacement = 100;

hearts_random = function(number_of_hearts, sprite_width, sprite_height, min_time, add_time) {
  return $('.heart').each(function() {
    return $(this).animate({
      top: sprite_height + Math.floor(Math.random() * ($(window).height() - (sprite_height * 2.0))),
      left: sprite_width + Math.floor(Math.random() * ($(window).width() - (sprite_width * 2.0)))
    }, min_time + Math.floor(Math.random() * add_time), function() {
      return hearts_random(number_of_hearts, sprite_width, sprite_height, min_time, add_time);
    });
  });
};

hearts_to_center = function() {
  return $('.heart').each(function() {
    return $(this).animate({
      top: Math.floor($(window).height() / 2),
      left: Math.floor($(window).width() / 2)
    }, 0);
  });
};

hearts_perlin = function() {
  x_displacement = Math.floor(($(window).width() - 126) * 0.5);
  $('.heart').each(function() {
    var x_calc;

    return x_calc = Math.floor((perlin.noise(x++) - 0.5) * x_displacement);
  });
  return $(this).animate({
    top: "+=" + x_calc,
    left: "+=" + x_calc
  }, 1000 + Math.floor(Math.random() * 5000), function() {
    return hearts_perlin();
  });
};

hearts_create_divs = function(number_of_hearts) {
  var i, _i, _results;

  _results = [];
  for (i = _i = 1; _i <= number_of_hearts; i = _i += 1) {
    _results.push($('body').append('<div class="heart"></div>'));
  }
  return _results;
};

hearts = function(no_of_hearts) {
  hearts_create_divs(no_of_hearts);
  hearts_to_center();
  return hearts_random(no_of_hearts, $('.heart first').width(), $('.heart first').height(), 500, 2000);
};

kill_all_hearts = function() {
  return $('.heart').remove();
};
